In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet


import warnings; warnings.simplefilter('ignore')

In [52]:
movies = pd.read_csv('/content/drive/MyDrive/LLM RAG Recommender - MovieLens/Data/ml-32m/movies_enriched.csv')

In [53]:
movies.head()

,movieId,tmdbId,title,overview,tagline,runtime,budget,revenue,release_date,genres,vote_average,vote_count,poster_path,director,cast,keywords,production_companies,collection_name,tmdb_recommendation_ids
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",The adventure takes off when toys come to life!,81,30000000,394436586,1995-11-22,"['Family', 'Comedy', 'Animation', 'Adventure']",7.970,19297,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,John Lasseter,"['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim...","['rescue', 'friendship', 'mission', 'jealousy'...",['Pixar'],Toy Story Collection,"[863, 9487, 10193, 8587, 585]"
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,It's a jungle in here.,104,65000000,262821940,1995-12-15,"['Adventure', 'Fantasy', 'Family']",7.242,10971,/iWV47r6kFneCiApgrMII5HSkfHw.jpg,Joe Johnston,"['Robin Williams', 'Kirsten Dunst', 'Bradley P...","['giant insect', 'board game', 'disappearance'...","['TriStar Pictures', 'Interscope Communication...",Jumanji Collection,"[353486, 6795, 788, 1593, 879]"
2,3,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,101,25000000,71500000,1995-12-22,"['Romance', 'Comedy']",6.500,409,/1FSXpj5e8l4KH6nVFO5SPUeraOt.jpg,Howard Deutch,"['Walter Matthau', 'Jack Lemmon', 'Ann-Margret...","['fishing', 'sequel', 'old man', 'best friend'...","['Lancaster Gate', 'Warner Bros. Pictures']",Grumpy Old Men Collection,"[11520, 39242, 24732, 30066, 50766]"
3,4,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,127,16000000,81452156,1995-12-22,"['Comedy', 'Drama', 'Romance']",6.260,179,/qJU6rfil5xLVb5HpJsmmfeSK254.jpg,Forest Whitaker,"['Whitney Houston', 'Angela Bassett', 'Loretta...","['based on novel or book', 'single mother', 'd...",['20th Century Fox'],NaN,"[31000, 21539, 16158, 33644, 64255]"
4,5,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just when his world is back to normal... he's ...,106,0,76594107,1995-12-08,"['Comedy', 'Family']",6.266,777,/rj4LBtwQ0uGrpBnCELr716Qo3mw.jpg,Charles Shyer,"['Steve Martin', 'Diane Keaton', 'Martin Short...","['daughter', 'baby', 'parent child relationshi...","['Touchstone Pictures', 'Sandollar Productions']",Father of the Bride (Steve Martin) Collection,"[11846, 65137, 22968, 14949, 13759]"

In [54]:
movies.shape

(86315, 19)

In [55]:
import numpy as np
from ast import literal_eval

# replacing nan with empty list []
movies['genres'] = movies['genres'].apply(lambda x: [] if x is np.nan else x)

# converting string into actual list which is the python object
movies['genres'] = movies['genres'].apply(lambda x: literal_eval(x) if isinstance(x, str) else x)

# Might remove later
movies['genres'] = movies['genres'].apply(lambda x: [i for i in x] if isinstance(x, list) else [])

In [56]:
movies['genres']

0        [Family, Comedy, Animation, Adventure]
1                  [Adventure, Fantasy, Family]
2                             [Romance, Comedy]
3                      [Comedy, Drama, Romance]
4                              [Comedy, Family]
                          ...
86310                                   [Drama]
86311                           [Drama, Comedy]
86312                                   [Drama]
86313                                   [Drama]
86314          [Documentary, Action, Adventure]
Name: genres, Length: 86315, dtype: object

In [57]:
movies.head(2)

,movieId,tmdbId,title,overview,tagline,runtime,budget,revenue,release_date,genres,vote_average,vote_count,poster_path,director,cast,keywords,production_companies,collection_name,tmdb_recommendation_ids
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",The adventure takes off when toys come to life!,81,30000000,394436586,1995-11-22,"[Family, Comedy, Animation, Adventure]",7.970,19297,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,John Lasseter,"['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim...","['rescue', 'friendship', 'mission', 'jealousy'...",['Pixar'],Toy Story Collection,"[863, 9487, 10193, 8587, 585]"
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,It's a jungle in here.,104,65000000,262821940,1995-12-15,"[Adventure, Fantasy, Family]",7.242,10971,/iWV47r6kFneCiApgrMII5HSkfHw.jpg,Joe Johnston,"['Robin Williams', 'Kirsten Dunst', 'Bradley P...","['giant insect', 'board game', 'disappearance'...","['TriStar Pictures', 'Interscope Communication...",Jumanji Collection,"[353486, 6795, 788, 1593, 879]"

In [58]:
movies['overview'] = movies['overview'].fillna('')
movies['tagline'] = movies['tagline'].fillna('')
movies['description'] = movies['overview'] + movies['tagline']
movies['title'] = movies['title'].fillna('')
movies['director'] = movies['director'].fillna('')


movies['keywords'] = movies['keywords'].apply(lambda x: [] if x is np.nan else x)
movies['keywords'] = movies['keywords'].apply(lambda x: literal_eval(x) if isinstance(x, str) else x)
movies['keywords'] = movies['keywords'].apply(lambda x: [i for i in x] if isinstance(x, list) else [])

movies['cast'] = movies['cast'].apply(lambda x: [] if x is np.nan else x)
movies['cast'] = movies['cast'].apply(lambda x: literal_eval(x) if isinstance(x, str) else x)
movies['cast'] = movies['cast'].apply(lambda x: [i for i in x] if isinstance(x, list) else [])
movies['cast'] = movies['cast'].apply(lambda x: x[:3] if len(x) >=3 else x)

movies['production_companies'] = movies['production_companies'].apply(lambda x: [] if x is np.nan else x)
movies['production_companies'] = movies['production_companies'].apply(lambda x: literal_eval(x) if isinstance(x, str) else x)
movies['production_companies'] = movies['production_companies'].apply(lambda x: [i for i in x] if isinstance(x, list) else [])
movies['production_companies'] = movies['production_companies'].apply(lambda x: x[:3] if len(x) >=3 else x)

In [59]:
movies.cast, movies.production_companies

(0                      [Tom Hanks, Tim Allen, Don Rickles]
 1          [Robin Williams, Kirsten Dunst, Bradley Pierce]
 2               [Walter Matthau, Jack Lemmon, Ann-Margret]
 3        [Whitney Houston, Angela Bassett, Loretta Devine]
 4               [Steve Martin, Diane Keaton, Martin Short]
                                ...
 86310          [Damián Alcázar, Grapa Paola, María Zubiri]
 86311    [Siobhan Fallon Hogan, Peter Macon, Robert Pat...
 86312    [Taraneh Alidoosti, Mahtab Keramati, Masoud Ka...
 86313      [Jan Sterling, James MacArthur, William Windom]
 86314                            [Ueli Steck, Dani Arnold]
 Name: cast, Length: 86315, dtype: object,
 0                                                  [Pixar]
 1        [TriStar Pictures, Interscope Communications, ...
 2                  [Lancaster Gate, Warner Bros. Pictures]
 3                                       [20th Century Fox]
 4             [Touchstone Pictures, Sandollar Productions]
                                ...
 86310               [Chullachaki Producciones, Gema Films]
 86311    [Emerald Caz Productions, Legendary Goat Produ...
 86312                [Andisheh Pardis Jam, Katara Studios]
 86313                  [Commonwealth United Entertainment]
 86314                                [Pitch International]
 Name: production_companies, Length: 86315, dtype: object)

In [60]:
movies.description

0        Led by Woody, Andy's toys live happily in his ...
1        When siblings Judy and Peter discover an encha...
2        A family wedding reignites the ancient feud be...
3        Cheated on, mistreated and stepped on, the wom...
4        Just when George Banks has recovered from his ...
                               ...
86310    Ronnie Monroy has had an unmeaningful life as ...
86311    A death row prisoner with 10 days left to live...
86312    Elham is a young, divorced Iranian woman. Seek...
86313    In Vietnam, aspiring actor Johnny Taylor is gi...
86314    Fearless alpine climbers Ueli Steck and Dani A...
Name: description, Length: 86315, dtype: object

In [61]:
movies['cast'] = movies['cast'].apply(lambda x: [str.lower(i.replace(" ", "")) for i in x])
movies['director'] = movies['director'].apply(lambda x: str.lower(x.replace(" ", "")))

In [62]:
def weighted_rating(x, m, C):
    v = x['vote_count']
    R = x['vote_average']
    return (v/(v+m) * R) + (m/(m+v) * C)

In [63]:
tfidf = TfidfVectorizer(stop_words='english', ngram_range=(1, 2), min_df=1)

In [64]:
tfidf_matrix = tfidf.fit_transform(movies['description'])

In [65]:
tfidf_matrix.shape

(86315, 1736558)

In [66]:
from ast import literal_eval
from sklearn.feature_extraction.text import CountVectorizer

In [67]:
def create_soup(x):
    return (
        ' '.join(x['keywords']) + ' ' +
        ' '.join(x['cast']) + ' ' +
        x['director'] + ' ' +
        ' '.join(x['genres']) + ' ' +
        ' '.join(x['production_companies'])
    )

movies['soup'] = movies.apply(create_soup, axis=1)

In [68]:
count = CountVectorizer(analyzer='word', ngram_range=(1, 1), min_df=1, stop_words='english')
count_matrix = count.fit_transform(movies['soup'])

In [69]:
count_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1332414 stored elements and shape (86315, 162458)>

In [70]:
from scipy.sparse import hstack

# Stack the two matrices horizontally
combined_matrix = hstack([tfidf_matrix, count_matrix])

In [71]:
combined_matrix.shape

(86315, 1899016)

In [72]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


movies = movies.reset_index()
indices = pd.Series(movies.index, index=movies['title'])
movies['year'] = pd.to_datetime(movies['release_date'], errors='coerce').dt.year

In [73]:
def get_recommendations_batch(titles, combined_matrix, movies_df, indices, batch_size=10, top_n=10, candidate_pool=50):

    results = {}

    # Process in batches
    for i in range(0, len(titles), batch_size):
        batch_titles = titles[i : i + batch_size]

        # Get valid indices
        batch_indices = []
        valid_titles = []

        for t in batch_titles:
            if t in indices:
                idx = indices[t]
                # Handle duplicate titles
                if isinstance(idx, (pd.Series, pd.Index, np.ndarray, list)):
                    idx = idx.iloc[0] if hasattr(idx, 'iloc') else idx[0]

                batch_indices.append(idx)
                valid_titles.append(t)
            else:
                print(f"Warning: '{t}' not found in indices.")

        if not batch_indices:
            continue

        # Extract feature vectors
        target_vectors = combined_matrix[batch_indices]

        # Compute cosine similarity
        batch_sim_scores = cosine_similarity(target_vectors, combined_matrix)

        # Process each movie
        for k, title in enumerate(valid_titles):
            scores = batch_sim_scores[k]

            top_indices = np.argpartition(scores, -(candidate_pool + 1))[-(candidate_pool + 1):]
            top_indices = top_indices[np.argsort(scores[top_indices])[::-1]]

            # Exclude input movie
            final_indices = [idx for idx in top_indices if idx != batch_indices[k]][:candidate_pool]

            # Get metadata
            recs = movies_df.iloc[final_indices][['title', 'vote_count', 'vote_average', 'year']].copy()
            recs['similarity'] = scores[final_indices]

            # Filter for Quality

            C = recs['vote_average'].mean()
            m = recs['vote_count'].quantile(0.20)
            recs = recs[recs['vote_count'] >= m]

            # Calculate Score
            recs['wr_score'] = recs.apply(lambda x: weighted_rating(x, m, C), axis=1)


            results[title] = recs.sort_values('similarity', ascending=False).head(top_n)

    return results

In [74]:
# import time


# test_movies = [
#     'Toy Story', 'Jumanji', 'Grumpier Old Men', 'Heat', 'Sabrina', 'Tom and Huck',
#     'Sudden Death', 'GoldenEye', 'The American President', 'Dracula: Dead and Loving It', 'The Batman'
# ]

# start = time.time()
# recs_1 = get_recommendations_batch(test_movies, combined_matrix, movies, indices, batch_size=1)
# end = time.time()
# print(f"Batch Size 1 took: {end - start:.4f} seconds")


# recs_10 = get_recommendations_batch(test_movies, combined_matrix, movies, indices, batch_size=1000)



# print(recs_10['The Batman'])

In [75]:
import time
import random

# Selecting 100 Random Movies
random_titles = movies['title'].sample(n=100, random_state=42).tolist()

print(f"Selected {len(random_titles)} random movies for testing.")
print(f"Examples: {random_titles[:5]}")




test_results = get_recommendations_batch(
    random_titles,
    combined_matrix,
    movies,
    indices,
    batch_size=1000,
    top_n=50,
    candidate_pool=100
)


# looking at random results to see if they make sense
for i in range(10):
    title = random_titles[i]
    print(f"\nSource Movie: {title}")
    if title in test_results:
        print(test_results[title][['title', 'similarity', 'wr_score']].head(100))
    else:
        print("No recommendations generated (possibly filtered out).")

Selected 100 random movies for testing.
Examples: ['The Penthouse', 'Jinn', 'Robot on the Road', 'Pigs 2: The Last Blood', 'Crooklyn']

Source Movie: The Penthouse
                            title  similarity  wr_score
52300            The Lost Brother    0.410391  6.778114
51611             Dead Slow Ahead    0.389490  6.482203
51579                 Mrs. Harris    0.382692  5.704024
79083            The Night Doctor    0.381771  6.445280
23937             Penthouse North    0.377815  5.710899
48371               The Next Skin    0.374634  5.696419
23614                  On the Ice    0.374634  6.108066
23992        The Body of My Enemy    0.368606  6.324577
39647         A Friend of Vincent    0.368563  5.787305
24059                       Prowl    0.368421  5.030127
83654                    Scorpion    0.368421  5.446472
67927                  Dirt Music    0.368421  6.138481
68112        The Crimes That Bind    0.367884  6.397501
15068              8th Wonderland    0.367884  6.051813
10263               Separate Lies    0.367884  5.748818
34350                     24 Days    0.367884  6.480244
36368                       Wazir    0.367065  6.602487
6610                   Demonlover    0.359937  5.789139
58253                  Viper Club    0.359862  5.512870
37988                        Amar    0.359303  4.670466
9915                  Vodka Lemon    0.359092  6.392259
20937        Cold Comes the Night    0.359092  5.411229
33335               An Open Heart    0.359092  5.458489
51475  Emmanuelle: Queen of Sados    0.359092  6.169835
18440             California Solo    0.359092  5.691786
37666        The Tree of Guernica    0.359092  5.939066
23112               So Much Water    0.359092  5.479956
62028              American Woman    0.359092  5.193382
75514              White on White    0.359092  5.900575
22395                  Copenhagen    0.359092  6.517831
45170                      Django    0.359092  6.255902
39646              The North Star    0.355966  6.031527
42821                Interruption    0.355516  6.358203
23196              Orders to Kill    0.355409  6.674021
55850               Close Enemies    0.355409  5.902408
9275            The Galíndez File    0.355409  4.756988
71351                   The Flood    0.353209  5.037305
8069                         Novo    0.351011  5.441938
35363            Adieu Philippine    0.350534  6.675345
20384         The Wonderful Crook    0.350438  5.554835
47351                        Moka    0.350438  6.004330
51827               Thirst Street    0.350438  4.780590
76601                  The Tunnel    0.350438  4.507133
85528      The Path of Excellence    0.350438  6.073274
60652                 French Tour    0.350438  5.382414
10173          L.A. Without a Map    0.350438  5.756917
61234                      Jaulas    0.345857  5.689258
79072     The Last Thing Mary Saw    0.344292  6.019387
60422                  L'Addition    0.344240  5.058203
61467                 22nd Of May    0.344124  6.007357

Source Movie: Jinn
                            title  similarity  wr_score
62708             My Soul to Keep    0.474342  5.345383
56034                Warning Shot    0.324443  5.333128
82374                      Sardar    0.294174  6.381013
61260                Winter Ridge    0.284096  5.240681
41302                        H8RZ    0.283473  5.348985
14640          The Forbidden Door    0.283473  6.282771
14184                 Defenseless    0.282843  5.133261
5152                  High Crimes    0.276079  6.341478
1026            Shadow Conspiracy    0.274013  5.076461
81510                    Stowaway    0.273861  6.062750
62337                    Deserted    0.273861  4.890627
19019           Blood of My Blood    0.273861  6.389985
39901    To the Ends of the Earth    0.273861  5.639985
61927               The Corrupted    0.273861  5.968587
35416                      Talvar    0.272166  7.327836
58691              Order of Chaos    0.267444  4.894557
46804                   Mudhalvan    0.267261  6.499277
7002                The Statement    0.265751  5.596339
23462        The Aggression Scale    0.265615  5.596299
66621                      Awoken    0.265540  5.681617
70383  May the Devil Take You Too    0.265165  6.619494
77620                   Dangerous    0.265165  5.987905
62932                       Spell    0.265165  5.214448
5234                   Unfaithful    0.258199  6.663711
30426                 Wild Horses    0.257696  4.931199
79320                  Glasshouse    0.257480  5.810965
40459               Guns for Hire    0.257395  4.980858
74623              I Am All Girls    0.257248  6.511563
59201                   Billy Boy    0.257248  5.048908
5672          The Weight of Water    0.257248  5.461962
56172                   Bel Canto    0.257248  5.420262
76899                      Plan A    0.257248  6.050246
6298             Cloak and Dagger    0.257248  6.313803
31962                The Invoking    0.257248  4.486594
82135           Dead for a Dollar    0.257248  5.821345
4573                 Original Sin    0.254000  6.090011
24641                   Malicious    0.250452  4.997583
55718                     Replace    0.250417  5.078993
67458          TRON: The Next Day    0.250241  5.681280
45325                       Bokeh    0.250176  5.423137
11081                     Sirocco    0.250000  5.807788
62793                  Jallikattu    0.250000  6.576092
56401                Bayou Caviar    0.250000  4.947891
61928                 Hellmington    0.250000  5.230271
63396            American Dreamer    0.250000  5.917488
6589                  See No Evil    0.250000  6.438323
15468                           M    0.250000  6.142822
8144         Whispers in the Dark    0.250000  5.052711
33776                   Big Match    0.250000  6.547491
1739          The Gingerbread Man    0.250000  5.574546

Source Movie: Robot on the Road
                                                   title  similarity  wr_score
61164                               Technological Threat    0.418121  5.888479
69513                           Live Freaky! Die Freaky!    0.358057  4.868091
46285                   Tamala 2010: A Punk Cat in Space    0.350823  6.230420
27133                                  Stitch! The Movie    0.346688  6.414412
49805                       The Centrifuge Brain Project    0.339683  6.749524
58939                                              Puppy    0.336646  7.154364
58938                              Panic in the Mailroom    0.336336  6.756564
22429                   LEGO Hero Factory: Savage Planet    0.336336  6.201412
71102               Jimmy Neutron: Win, Lose and Kaboom!    0.336336  6.632486
68199  Phineas and Ferb the Movie: Candace Against th...    0.336336  7.233364
77061                                            Tempbot    0.336323  6.236092
38462                                            Hot Bot    0.335142  4.367130
56121                                            Big Ear    0.334497  6.525604
19256                       Tripping the Rift: The Movie    0.334497  5.421723
69756                            Trump vs the Illuminati    0.334497  3.785814
66606                                           Marooned    0.328335  6.451857
66213                 Giant God Warrior Appears in Tokyo    0.326357  6.506834
11483  Aqua Teen Hunger Force Colon Movie Film for Th...    0.326357  6.468935
55926                                           Next Gen    0.321058  6.988818
53093                               Mazinger Z: Infinity    0.320256  6.879147
81816                                 Fifty Percent Grey    0.320256  6.165533
85758                LEGO Star Wars: The Quest for R2-D2    0.320256  5.716185
58541                    Friends: Naki on Monster Island    0.320256  6.823049
7757                                      Robot Carnival    0.319173  6.599251
61368                     Invader Zim: Enter the Florpus    0.318142  7.327308
73169                  DreamWorks Home: For the Holidays    0.318142  5.406015
47281                                               MFKZ    0.318142  7.115925
56728                    The Satellite Girl and Milk Cow    0.318142  6.735739
15850              Evangelion: 2.0 You Can (Not) Advance    0.314945  7.772262
66865  Doraemon: Nobita and the New Steel Troops: Win...    0.311395  7.176261
80885                                  Brian and Charles    0.310726  6.315632
23161                          Scooby-Doo! Frankencreepy    0.310087  7.571445
51882             LEGO DC Comics Super Heroes: The Flash    0.310087  6.796905
47253                                              Cream    0.309016  7.006990
12477                                       Space Chimps    0.309016  4.923498
17720                    Dr. Goldfoot and the Girl Bombs    0.308145  5.136413
76610                                     Planet Unknown    0.307692  6.447937
85759                      LEGO Star Wars: Bombad Bounty    0.307692  6.137912
64083                               Ship of the Monsters    0.303822  6.158177
28626                                        Malice@Doll    0.303175  5.520596
71752                                  Jojo in the Stars    0.302952  6.218340
49335                                Batman vs. Two-Face    0.302614  6.288229
55084                            Tales from the Far Side    0.302614  6.671773
64050                        Spider-Ham: Caught in a Ham    0.302614  6.822563
85760               LEGO Star Wars: Revenge of The Brick    0.302614  5.991731
66364                                 Sex and the Future    0.299075  5.418879
64176                                      (UN)Ideal Man    0.298881  5.442190
45639                                    Genocidal Organ    0.298881  6.572974
32705                                  OMG, I'm a Robot!    0.298700  6.231727
55794  Ghost in the Shell: S.A.C. 2nd GIG - Individua...    0.297088  7.388708

Source Movie: Pigs 2: The Last Blood
                                                  title  similarity  wr_score
46351                                              Pigs    0.485947  6.968431
66974                                            Pigs 3    0.431620  6.438437
62537                                     Law of Tehran    0.366963  7.127507
56940                                             Reich    0.365843  5.269516
35122                                  With Clean Hands    0.354317  6.958822
65895                                     Panther Squad    0.353553  4.060425
35607                  Rome, the Other Face of Violence    0.351566  5.670585
67147                                             Kroll    0.351329  6.440725
26815                                             Ricco    0.351192  5.721268
51752                                         Gentleman    0.350823  6.751129
33500                           The Sicilian Connection    0.338266  5.527687
42586                                           Tik Tok    0.337570  5.706862
26693                   Death Is Nimble, Death Is Quick    0.329917  5.560551
83767                      Johan Falk: Silent Diplomacy    0.328529  6.095125
50422                                   Polish Roulette    0.327966  5.596894
36221                                        Dossier K.    0.318694  6.330743
41505                                  Fear in the City    0.318384  5.292425
34511                                     Killer Tattoo    0.317209  6.334731
23651                                     Silent Action    0.316707  5.455723
57871                           Iravukku Aayiram Kangal    0.316648  6.404975
81530                                     Surfers’ Time    0.316602  6.196032
7160                                           Raw Deal    0.313192  5.826191
80806                                            Vikram    0.312313  7.512283
23938  Johan Falk: GSI - Gruppen för särskilda insatser    0.307673  6.456889
6345                                             Tycoon    0.306786  5.353061
83764                        Johan Falk: Blood Diamonds    0.306786  6.582804
30036                                             Shool    0.301848  6.497057
23344                               A Man Called Magnum    0.300721  5.431929
31535                                     Go Gorilla Go    0.300642  6.354668
47767                             S.W.A.T.: Under Siege    0.300000  5.896823
46484                                         Racketeer    0.300000  6.616468
36100                                           Manhunt    0.300000  6.081312
31665                                 Going by the Book    0.299490  7.212213
45404                       The Story of the Kelly Gang    0.298142  5.290195
47037                        The Surrender of Tournavos    0.298142  5.137892
10446                              Executive Protection    0.293710  6.167796
37406                                           Pitbull    0.291991  6.387581
22421   A Better Tomorrow III: Love and Death in Saigon    0.290529  6.348272
80349                                    The Flying Ace    0.290518  5.896468
33110                                   Stolen Identity    0.290191  5.137021
83765                              Johan Falk: Lockdown    0.289212  6.997859
57968                                 Pitbull. Last Dog    0.288454  5.925219
23939                           Johan Falk: Vapenbröder    0.287870  6.387581
28780                                      Crimebusters    0.287242  5.370585
27167                              Women in Cellblock 9    0.286901  4.947803
41490                              Johan Falk: Leo Gaut    0.286883  6.049638
17204                                    The Dark House    0.286734  6.390103
41487                     Johan Falk: Barninfiltratören    0.286285  6.376109
49344                                          Agitator    0.286039  6.278627
37006                                           Ajnabee    0.286039  5.544479

Source Movie: Crooklyn
                                           title  similarity  wr_score
157                                     Clockers    0.417957  6.665503
3312                                Jungle Fever    0.396059  6.359578
3311                            Mo' Better Blues    0.374351  6.467357
66040                  The King of Staten Island    0.365760  6.991749
3308                         She's Gotta Have It    0.365636  6.615787
3310                          Do the Right Thing    0.360977  7.783308
8549               Love with the Proper Stranger    0.359097  6.631957
68891                                       Soul    0.353776  8.099598
2626                      Brighton Beach Memoirs    0.350477  6.419794
10261                    The Squid and the Whale    0.348302  6.936979
3309                                 School Daze    0.343171  5.702704
2592                               Summer of Sam    0.330566  6.483430
19058                            Red Hook Summer    0.326896  5.721057
3017                           Sweet and Lowdown    0.324063  6.731731
4989                                  Funny Lady    0.323616  5.372758
48346                               Little Boxes    0.322259  6.081517
21433                                Begin Again    0.321403  7.228409
27468                             Gimme the Loot    0.315177  6.138600
23006                           Listen Up Philip    0.313112  5.861514
6734                             Pieces of April    0.306844  6.468649
628                                       Girl 6    0.302868  5.078915
15156                        Come Blow Your Horn    0.300123  5.389063
35570                                    Chi-Raq    0.300123  5.744795
8192                    All I Want For Christmas    0.300123  5.654235
9357                                 She Hate Me    0.300123  5.222107
28649                              One More Time    0.299804  5.281755
28544                    Da Sweet Blood of Jesus    0.297044  5.014899
53070                           Hearts Beat Loud    0.294622  6.803669
19396                                     Bad 25    0.293057  7.043160
24140                           Cops and Robbers    0.291783  6.107900
8080                                The Sting II    0.290020  5.050127
66205                           A Dog Named Duke    0.286079  6.432270
46660  The Meyerowitz Stories (New and Selected)    0.285978  6.455595
33661            Just Another Girl on the I.R.T.    0.284850  6.428537
6993                                       Honey    0.284566  6.295827
65706                                        Abe    0.283928  6.726067
66985                 Long Nights Short Mornings    0.283148  5.289523
38690       Bela Lugosi Meets a Brooklyn Gorilla    0.281801  4.277688
28791                       Appropriate Behavior    0.281220  6.257370
6933                          That Touch of Mink    0.277218  6.364895
12986                                 Two Lovers    0.274618  6.839453
77997                                 The Humans    0.274618  6.076704
32876                                  Club Life    0.274398  5.182736
10638                                 Inside Man    0.273617  7.392944
29053                                Dirty Hands    0.271163  6.307900
28492                            Without a Trace    0.270546  5.512434
1025                              Get on the Bus    0.269676  6.243785
2051                      Slums of Beverly Hills    0.269311  6.259636
35512                               Downtown '81    0.269069  6.408530
42780                                    Honey 2    0.269069  6.287878

Source Movie: The Condemned of Altona
                                   title  similarity  wr_score
33771               Girl with a Suitcase    0.435664  7.038592
10314                        The Swindle    0.385758  7.271196
30185                      The Swindlers    0.385758  6.149504
65587          When You Read This Letter    0.350506  5.915999
30188  Policarpo, ufficiale di scrittura    0.334011  6.912788
29752           Venice, the Moon and You    0.333943  5.882196
37902                     Violent Summer    0.331482  7.111874
7618                  Sodom and Gomorrah    0.331133  5.486758
33589                 Poor But Beautiful    0.320256  6.662277
17542                     The Vanquished    0.320256  6.307352
33588                Scandal in Sorrento    0.306186  6.872931
30198                  The Sign of Venus    0.306186  6.758261
29751                    Fiasco in Milan    0.288675  6.826428
74025                 Duel of the Titans    0.288675  5.497005
28848                           Paranoia    0.280056  5.924779
36069                           The Roof    0.263190  7.195489
7982                         The Leopard    0.261666  7.686853
48206        The Miller's Beautiful Wife    0.261116  5.566240
3689                           Two Women    0.255730  7.777264
17161                 The Gold of Naples    0.250582  7.237841
15985                    The Rothschilds    0.241258  6.087929
68029                        Finis Terræ    0.240192  6.857813
5548                       The Grey Zone    0.231125  6.578888
14045             Marriage Italian Style    0.223607  7.677800
10040               General Della Rovere    0.222222  7.350953
27707              His Days are Numbered    0.218218  6.994868
64834                Bandits of Orgosolo    0.218218  7.303065
8541             The Four Days of Naples    0.216506  7.326510
6458          The Man in the Glass Booth    0.213507  6.162686
24024              Dangerously They Live    0.207689  6.117909
15571                      Days of Glory    0.204869  5.932927
25156                    The Rose Garden    0.204639  6.372275
22173               She Devils of the SS    0.204579  5.121615
40524         Next Year If All Goes Well    0.204124  5.874129
34884                             Frisky    0.204124  7.086808
15748             The Silence of the Sea    0.201704  7.443638

In [76]:
#Trying the weighted approach

In [77]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# 1. Define Vectorizers
count_vec = CountVectorizer(stop_words='english', min_df=1)
tfidf_vec = TfidfVectorizer(stop_words='english', min_df=1)

# 2. Fit Separate Matrices
# We assume your 'movies' dataframe already has these columns cleaned
print("Building separate matrices...")

# Matrix A: Description (Plot)
mat_desc = tfidf_vec.fit_transform(movies['description'])

# Matrix B: Keywords (Plot elements)
# (If keywords are lists, join them first: movies['keywords'].apply(lambda x: ' '.join(x)))
mat_keywords = count_vec.fit_transform(movies['keywords'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x))

# Matrix C: Director (Style/Vibe)
mat_director = count_vec.fit_transform(movies['director'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x))

# Matrix D: Genres (Category)
mat_genres = count_vec.fit_transform(movies['genres'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x))

# Matrix E: Cast (Star Power)
mat_cast = count_vec.fit_transform(movies['cast'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x))

mat_production = count_vec.fit_transform(movies['production_companies'].apply(lambda x: ' '.join(x) if isinstance(x, list) else x))

mat_title = tfidf_vec.fit_transform(movies['title'])

Building separate matrices...

In [78]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

def get_weighted_recommendations(title, weights, movies_df, indices, top_n=20):
    """
    weights: Dictionary of weights, e.g., {'desc': 0.1, 'director': 0.5, ...}
    """
    if title not in indices:
        return "Movie not found."

    idx = indices[title]

    # Handle duplicate titles
    if isinstance(idx, (pd.Series, pd.Index, np.ndarray, list)):
        idx = idx.iloc[0]


    # Description
    sim_desc = cosine_similarity(mat_desc[idx], mat_desc).flatten()

    # Keywords
    sim_keywords = cosine_similarity(mat_keywords[idx], mat_keywords).flatten()

    # Director (Crucial for vibe!)
    sim_director = cosine_similarity(mat_director[idx], mat_director).flatten()

    # Genres
    sim_genres = cosine_similarity(mat_genres[idx], mat_genres).flatten()

    # Cast
    sim_cast = cosine_similarity(mat_cast[idx], mat_cast).flatten()

    sim_production = cosine_similarity(mat_production[idx], mat_production).flatten()

    sim_title = cosine_similarity(mat_title[idx], mat_title).flatten()
    # Calculating Weighted Average Score

    final_score = (
        (sim_desc * weights.get('desc', 0)) +
        (sim_keywords * weights.get('keywords', 0)) +
        (sim_director * weights.get('director', 0)) +
        (sim_genres * weights.get('genres', 0)) +
        (sim_cast * weights.get('cast', 0)) +
        (sim_production * weights.get('production', 0)) +
        (sim_title * weights.get('title', 0))
    )


    # Get top candidates
    candidate_pool = 100
    top_indices = np.argpartition(final_score, -(candidate_pool + 1))[-(candidate_pool + 1):]
    top_indices = top_indices[np.argsort(final_score[top_indices])[::-1]]

    # Excluding the movie itself
    final_indices = [i for i in top_indices if i != idx]

    # Metadata
    recs = movies_df.iloc[final_indices][['title', 'vote_count', 'vote_average', 'year']].copy()


    recs['sim_total'] = final_score[final_indices]
    recs['sim_director'] = sim_director[final_indices]
    recs['sim_desc'] = sim_desc[final_indices]
    recs['sim_keywords'] = sim_keywords[final_indices]
    recs['sim_production'] = sim_production[final_indices]
    recs['sim_title'] = sim_title[final_indices]

    # Weighted Rating Sort
    C = recs['vote_average'].mean()
    m = recs['vote_count'].quantile(0.30)
    recs = recs[recs['vote_count'] >= m]
    recs['wr_score'] = recs.apply(lambda x: weighted_rating(x, m, C), axis=1)

    return recs.sort_values('sim_total', ascending=False).head(top_n)

In [79]:
import pandas as pd


custom_weights = {
    'desc': 0.2,
    'keywords': 0.4,
    'director': 0.5,
    'genres': 0.4,
    'production': 0.2,
    'cast': 0.2,
    'title': 0.3
}

results = get_weighted_recommendations("The Dark Knight Rises", custom_weights, movies, indices)
print(results[['title', 'sim_total', 'sim_director', 'sim_desc', 'wr_score', 'sim_keywords', 'sim_production', 'sim_title']])

                                 title  sim_total  sim_director  sim_desc  \
12165                  The Dark Knight   1.535447           1.0  0.325888
9960                     Batman Begins   1.214011           1.0  0.202808
5258                          Insomnia   0.896266           1.0  0.000000
47062                          Dunkirk   0.876054           1.0  0.000000
2471                         Following   0.840653           1.0  0.030851
66470                            Tenet   0.828835           1.0  0.000000
84910                      Oppenheimer   0.811961           1.0  0.000000
20984                     Interstellar   0.745056           1.0  0.000000
11115                     The Prestige   0.740752           1.0  0.013564
14844                        Inception   0.740284           1.0  0.000000
4102                           Memento   0.688441           1.0  0.000000
4510                      The Punisher   0.574132           0.0  0.011972
4077                     Double Impact   0.539771           0.0  0.004807
8                         Sudden Death   0.514232           0.0  0.000000
83505   Detective Knight: Independence   0.509566           0.0  0.063346
66616  The Last Days of American Crime   0.508024           0.0  0.000000
27889                         Child 44   0.502967           0.0  0.000000
3434                      Marathon Man   0.497268           0.0  0.021556
21068                   Need for Speed   0.495332           0.0  0.004302
86285                 Desperation Road   0.494923           0.0  0.005245

       wr_score  sim_keywords  sim_production  sim_title
12165  8.517048      0.381693        0.632456   0.748113
9960   7.693015      0.350931        0.600000   0.000000
5258   6.941438      0.033352        0.182574   0.000000
47062  7.442592      0.027086        0.338062   0.000000
2471   7.051196      0.000000        0.258199   0.000000
66470  7.166818      0.098480        0.447214   0.000000
84910  8.026763      0.126350        0.600000   0.000000
20984  8.456860      0.088779        0.547723   0.000000
11115  8.192807      0.029361        0.298142   0.000000
14844  8.364114      0.034483        0.632456   0.000000
4102   8.164999      0.026261        0.182574   0.000000
4510   5.841786      0.344828        0.169031   0.000000
4077   6.204507      0.197952        0.298142   0.000000
8      6.035081      0.103005        0.365148   0.000000
83505  5.649663      0.131306        0.000000   0.326547
66616  6.472120      0.262613        0.282843   0.000000
27889  6.277506      0.047946        0.338062   0.000000
3434   7.093084      0.074278        0.316228   0.000000
21068  6.396646      0.053606        0.365148   0.000000
86285  6.504600      0.065653        0.338062   0.000000

In [80]:
test_movies = movies['title'].sample(n=100, random_state=42).tolist()

for movie in test_movies:
    results = get_weighted_recommendations(movie, custom_weights, movies, indices)
    print(f"\nSource Movie: {movie}")
    print(results[['title', 'sim_total', 'sim_director', 'sim_desc', 'wr_score', 'sim_keywords', 'sim_production', 'sim_title']])

# results = get_weighted_recommendations("The Dark Knight Rises", custom_weights, movies, indices)
# print(results[['title', 'sim_total', 'sim_director', 'sim_desc', 'wr_score', 'sim_keywords', 'sim_production', 'sim_title']])

Source Movie: The Penthouse
                           title  sim_total  sim_director  sim_desc  wr_score  \
23937            Penthouse North   0.874865           0.0  0.242440  5.700393
17233                     Fright   0.859290           1.0  0.013856  5.918764
28994                Open Season   0.826599           1.0  0.000000  5.368057
29048       The Long Day's Dying   0.766667           1.0  0.000000  5.356483
20890   And Then There Were None   0.703143           1.0  0.000000  5.661761
23466   Straight On Till Morning   0.701808           1.0  0.009042  5.624405
4806               The Earthling   0.667466           1.0  0.020834  5.981774
74159              The Penthouse   0.662801           0.0  0.199790  4.287146
6746             The Italian Job   0.641421           1.0  0.000000  6.956345
12125                    Descent   0.621320           0.0  0.000000  4.463193
4838   The Business of Strangers   0.592985           0.0  0.012090  5.510064
60878            Puthiya Niyamam   0.592771           0.0  0.000000  6.002666
15290                 Seven Days   0.581064           0.0  0.000000  6.232960
29046        The Man Called Noon   0.561721           1.0  0.000000  5.681973
12939        The Lazarus Project   0.558544           0.0  0.000000  5.946948
14841             The Front Line   0.558218           0.0  0.011693  5.922576
75526                       K.O.   0.551186           0.0  0.000000  5.503447
37346               Daniel & Ana   0.541888           0.0  0.000000  6.591807
75154                  The Track   0.537335           0.0  0.010550  6.473298
42844               The Salesman   0.536575           0.0  0.009263  7.223760

       sim_keywords  sim_production  sim_title
23937      0.158114        0.617213   0.798964
17233      0.124035        0.534522   0.000000
28994      0.000000        0.000000   0.000000
29048      0.000000        0.000000   0.000000
20890      0.000000        0.308607   0.000000
23466      0.000000        0.000000   0.000000
4806       0.000000        0.000000   0.000000
74159      0.100000        0.000000   1.000000
6746       0.000000        0.000000   0.000000
12125      0.286039        0.534522   0.000000
4838       0.258199        0.436436   0.000000
60878      0.447214        0.436436   0.000000
15290      0.258199        0.755929   0.000000
29046      0.000000        0.308607   0.000000
12939      0.129099        0.534522   0.000000
14841      0.447214        0.251976   0.000000
75526      0.000000        0.755929   0.000000
37346      0.069007        0.571429   0.000000
75154      0.338062        0.000000   0.000000
42844      0.210819        0.251976   0.000000

Source Movie: Jinn
                          title  sim_total  sim_director  sim_desc  wr_score  \
62708           My Soul to Keep   0.982843           1.0  0.000000  5.195545
58691            Order of Chaos   0.542329           0.0  0.004540  4.726818
46804                 Mudhalvan   0.541421           0.0  0.000000  6.428247
59656  D@bbe: Curse of the Jinn   0.524581           0.0  0.110930  5.358685
1026          Shadow Conspiracy   0.516480           0.0  0.005050  5.017854
965         The Rich Man's Wife   0.515470           0.0  0.000000  5.314291
2083               Stage Fright   0.506904           0.0  0.000000  6.732630
39901  To the Ends of the Earth   0.506904           0.0  0.000000  5.466417
61260              Winter Ridge   0.504724           0.0  0.023621  5.127238
22602                     Crush   0.503801           0.0  0.019005  5.956631
65064              Cruel Hearts   0.503522           0.0  0.017609  6.050845
46593        Kitten with a Whip   0.500000           0.0  0.000000  5.137204
85169    Fear the Invisible Man   0.500000           0.0  0.000000  6.095345
21646                     Favor   0.500000           0.0  0.000000  5.678237
10004                  Deceived   0.500000           0.0  0.000000  5.677302
17779              City of Fear   0.500000           0.0  0.000000  5.933897
71254                    Muscle   0.500000           0.0  0.000000  5.388173
7212               Taking Lives   0.486612           0.0  0.006657  6.370607
16584                  Cornered   0.484039           0.0  0.011948  5.882057
14494             Hotel Reserve   0.483824           0.0  0.010870  5.871785

       sim_keywords  sim_production  sim_title
62708           0.0        1.000000   0.000000
58691           0.0        0.707107   0.000000
46804           0.0        0.707107   0.000000
59656           0.0        0.408248   0.632686
1026            0.0        0.577350   0.000000
965             0.0        0.577350   0.000000
2083            0.0        0.534522   0.000000
39901           0.0        0.534522   0.000000
61260           0.0        0.500000   0.000000
22602           0.0        0.500000   0.000000
65064           0.0        0.500000   0.000000
46593           0.0        0.500000   0.000000
85169           0.0        0.500000   0.000000
21646           0.0        0.500000   0.000000
10004           0.0        0.500000   0.000000
17779           0.0        0.500000   0.000000
71254           0.0        0.500000   0.000000
7212            0.0        0.426401   0.000000
16584           0.0        0.408248   0.000000
14494           0.0        0.408248   0.000000

Source Movie: Robot on the Road
                                       title  sim_total  sim_director  \
7903                                I, Robot   0.772194           0.0
7757                          Robot Carnival   0.758173           0.0
38462                                Hot Bot   0.751062           0.0
7626               Jin-Roh: The Wolf Brigade   0.744949           1.0
7546                               Robot Jox   0.727020           0.0
77093                              E N V O Y   0.682843           0.0
21521                       A Letter to Momo   0.678885           1.0
11597                          Robot Monster   0.655448           0.0
77061                                Tempbot   0.644028           0.0
17720        Dr. Goldfoot and the Girl Bombs   0.633064           0.0
30251                        Catherine and I   0.629253           0.0
30491                        Robot Overlords   0.628808           0.0
18316                          Robot & Frank   0.625522           0.0
57723                             F.R.E.D.I.   0.621225           0.0
64176                          (UN)Ideal Man   0.620713           0.0
26811                   Robosapien: Rebooted   0.615089           0.0
15850  Evangelion: 2.0 You Can (Not) Advance   0.603938           0.0
33204                             Robot Wars   0.602874           0.0
46559                        Robot Holocaust   0.586902           0.0
42809                         Crash and Burn   0.585428           0.0

       sim_desc  wr_score  sim_keywords  sim_production  sim_title
7903   0.054208  6.954687      0.729800             0.0   0.794974
7757   0.000000  6.460461      0.612372             0.0   0.556045
38462  0.023257  4.453619      1.000000             0.0   0.000000
7626   0.000000  7.341630      0.000000             0.0   0.000000
7546   0.082458  5.548475      0.834058             0.0   0.486551
77093  0.000000  6.158030      1.000000             0.0   0.000000
21521  0.000000  7.241668      0.000000             0.0   0.000000
11597  0.039573  4.746988      0.577350             0.0   0.618844
77061  0.073876  6.067337      0.707107             0.0   0.000000
17720  0.019056  5.230935      0.707107             0.0   0.000000
30251  0.000000  5.425734      0.707107             0.0   0.000000
30491  0.000000  4.924481      0.707107             0.0   0.486551
18316  0.100759  6.889257      0.408248             0.0   0.579144
57723  0.106124  5.947144      1.000000             0.0   0.000000
64176  0.000000  5.508030      0.801784             0.0   0.000000
26811  0.075447  5.519557      1.000000             0.0   0.000000
15850  0.000000  7.739178      0.384900             0.5   0.000000
33204  0.037923  4.688690      0.534522             0.0   0.604935
46559  0.045454  4.043076      0.333333             0.0   0.538785
42809  0.032714  4.869917      1.000000             0.0   0.000000

Source Movie: Pigs 2: The Last Blood
                              title  sim_total  sim_director  sim_desc  \
66974                        Pigs 3   1.341007           1.0  0.305189
46351                          Pigs   1.257452           1.0  0.254421
57968             Pitbull. Last Dog   0.918243           1.0  0.091215
56940                         Reich   0.901912           1.0  0.026309
67147                         Kroll   0.817348           1.0  0.017705
80414        The Resistance Fighter   0.673573           1.0  0.051370
46353                 Demons of War   0.613261           1.0  0.014752
51752                     Gentleman   0.563299           0.0  0.000000
18735                     Aftermath   0.547140           1.0  0.000000
21596                   Jack Strong   0.510251           1.0  0.051255
37406                       Pitbull   0.501526           0.0  0.218955
21207                  In the Blood   0.497394           0.0  0.000000
41505              Fear in the City   0.494998           0.0  0.066741
72623                   Enforcement   0.494550           0.0  0.064502
23344           A Man Called Magnum   0.486742           0.0  0.025462
28836     Free Hand for a Tough Cop   0.481860           0.0  0.075965
35471                    Street Law   0.481650           0.0  0.000000
30036                         Shool   0.478217           0.0  0.057751
21483  Once Upon a Time in Shanghai   0.473030           0.0  0.000000
24797            Rulers of the City   0.473030           0.0  0.000000

       wr_score  sim_keywords  sim_production  sim_title
66974  6.398461           0.0        0.000000   0.822118
46351  6.917258           0.0        0.000000   0.822118
57968  5.925940           0.0        0.000000   0.000000
56940  5.392706           0.0        0.235702   0.000000
67147  6.377477           0.0        0.235702   0.000000
80414  6.105584           0.0        0.000000   0.000000
46353  6.263979           0.0        0.218218   0.000000
51752  6.619454           0.0        0.816497   0.000000
18735  6.499040           0.0        0.235702   0.000000
21596  6.436450           0.0        0.000000   0.000000
37406  6.349204           0.0        0.288675   0.000000
21207  5.810191           0.0        0.000000   0.569317
41505  5.411373           0.0        0.408248   0.000000
72623  6.311687           0.0        0.408248   0.000000
23344  5.521716           0.0        0.408248   0.000000
28836  6.498299           0.0        0.333333   0.000000
35471  6.310201           0.0        0.408248   0.000000
30036  6.400106           0.0        0.333333   0.000000
21483  7.000613           0.0        0.365148   0.000000
24797  6.189527           0.0        0.365148   0.000000

Source Movie: Crooklyn
                              title  sim_total  sim_director  sim_desc  \
3310             Do the Right Thing   1.074610           1.0  0.086300
628                          Girl 6   1.029835           1.0  0.019235
3821                     Bamboozled   1.019792           1.0  0.095009
9357                    She Hate Me   1.008866           1.0  0.000000
157                        Clockers   1.001413           1.0  0.000000
3309                    School Daze   0.965754           1.0  0.015364
3312                   Jungle Fever   0.944949           1.0  0.000000
1738                    He Got Game   0.938170           1.0  0.000000
35570                       Chi-Raq   0.935465           1.0  0.000000
3308            She's Gotta Have It   0.934574           1.0  0.000000
2592                  Summer of Sam   0.920259           1.0  0.171796
66262                   Da 5 Bloods   0.892655           1.0  0.000000
5818                      25th Hour   0.883908           1.0  0.010339
10638                    Inside Man   0.877149           1.0  0.000000
3134                      Malcolm X   0.868655           1.0  0.000000
3311               Mo' Better Blues   0.863299           1.0  0.000000
54353                BlacKkKlansman   0.852776           1.0  0.000000
1025                 Get on the Bus   0.848511           1.0  0.062142
3744   The Original Kings of Comedy   0.810056           1.0  0.078874
28544       Da Sweet Blood of Jesus   0.796633           1.0  0.000000

       wr_score  sim_keywords  sim_production  sim_title
3310   7.765348      0.278019        0.816497        0.0
628    5.250186      0.000000        0.629941        0.0
3821   6.202501      0.000000        0.503953        0.0
9357   5.373618      0.000000        0.544331        0.0
157    6.641136      0.270369        0.816497        0.0
3309   5.788604      0.000000        0.680414        0.0
3312   6.353115      0.204124        0.816497        0.0
1738   6.715908      0.048113        0.680414        0.0
35570  5.791528      0.000000        0.544331        0.0
3308   6.594816      0.314270        0.544331        0.0
2592   6.474192      0.216295        0.680414        0.0
66262  6.437739      0.000000        0.629941        0.0
5818   7.299962      0.121268        0.666667        0.0
10638  7.388720      0.181071        0.707107        0.0
3134   7.514031      0.105409        0.632456        0.0
3311   6.451144      0.000000        0.816497        0.0
54353  7.485063      0.038749        0.272166        0.0
1025   6.247646      0.000000        0.680414        0.0
3744   6.317520      0.000000        0.471405        0.0
28544  5.280682      0.000000        0.666667        0.0

Source Movie: The Condemned of Altona
                                  title  sim_total  sim_director  sim_desc  \
36069                          The Roof   0.974365           1.0  0.083149
3689                          Two Women   0.953433           1.0  0.033944
2977                    Bicycle Thieves   0.907707           1.0  0.038536
1121       The Children Are Watching Us   0.902944           1.0  0.014720
6464                         Umberto D.   0.900000           1.0  0.000000
8426                          Shoeshine   0.900000           1.0  0.000000
17161                The Gold of Naples   0.854436           1.0  0.024633
14890                         Sunflower   0.849509           1.0  0.000000
14045            Marriage Italian Style   0.797607           1.0  0.000000
6591   Indiscretion of an American Wife   0.787409           1.0  0.022830
21792                A Place for Lovers   0.787141           1.0  0.021489
4299   The Garden of the Finzi-Continis   0.786615           1.0  0.018861
29207                 Woman Times Seven   0.782843           1.0  0.000000
13454                  A Brief Vacation   0.782843           1.0  0.000000
36067      A Garibaldian in the Convent   0.730940           1.0  0.000000
9839                   Miracle in Milan   0.730940           1.0  0.000000
65587         When You Read This Letter   0.583538           0.0  0.023263
8006      Yesterday, Today and Tomorrow   0.566667           1.0  0.000000
7982                        The Leopard   0.566662           0.0  0.042741
30185                     The Swindlers   0.563299           0.0  0.000000

       wr_score  sim_keywords  sim_production  sim_title
36069  7.086961           0.0        0.288675        0.0
3689   7.758178           0.0        0.530330        0.0
2977   8.164351           0.0        0.000000        0.0
1121   7.396839           0.0        0.000000        0.0
6464   7.865228           0.0        0.000000        0.0
8426   7.684732           0.0        0.000000        0.0
17161  7.188655           0.0        0.000000        0.0
14890  7.391708           0.0        0.000000        0.0
14045  7.659116           0.0        0.000000        0.0
6591   5.976141           0.0        0.000000        0.0
21792  5.448234           0.0        0.000000        0.0
4299   6.866936           0.0        0.000000        0.0
29207  6.255259           0.0        0.000000        0.0
13454  5.976503           0.0        0.000000        0.0
36067  6.413267           0.0        0.000000        0.0
9839   7.235600           0.0        0.000000        0.0
65587  5.983124           0.0        0.894427        0.0
8006   7.403040           0.0        0.000000        0.0
7982   7.675657           0.0        0.790569        0.0
30185  6.165552           0.0        0.816497        0.0

Source Movie: The Girl with the Hat Box
                                                   title  sim_total  \
74030                              The House on Trubnaya   1.100000
76203                                        Live in Joy   0.800000
14054                              By the Bluest of Seas   0.733839
13890                                          Outskirts   0.730940
61706                                        Chess Fever   0.662585
29382                                       Striped Trip   0.635409
14185                                     Silent Wedding   0.633610
53591                                         Adam's Rib   0.620309
4466                                         The Experts   0.609441
46879                                  Zigzag of Success   0.602064
13830  The Extraordinary Adventures of Mr. West in th...   0.600000
71584                                 The Man in the Hat   0.594615
47825                                            The Box   0.574205
12120                                   Which Way Is Up?   0.570561
13953                              The Italian Straw Hat   0.546922
71834                                          Miss Mend   0.546196
46962                                      The Straw Hat   0.542448
23704                                       First a Girl   0.538228
29247                                       He's My Girl   0.533828
7355                                    Monster in a Box   0.528689

       sim_director  sim_desc  wr_score  sim_keywords  sim_production  \
74030           1.0  0.000000  6.008598      0.500000             0.0
76203           0.0  0.000000  5.535195      1.000000             0.0
14054           1.0  0.014493  6.155720      0.000000             0.0
13890           1.0  0.000000  6.053741      0.000000             0.0
61706           0.0  0.024251  6.181484      0.000000             1.0
29382           0.0  0.022345  6.757462      0.577350             0.0
14185           0.0  0.013350  7.065490      1.000000             0.0
53591           0.0  0.054339  5.234687      0.816497             0.0
4466            0.0  0.000000  4.643761      0.816497             0.0
46879           0.0  0.010322  6.222931      0.500000             0.0
13830           0.0  0.000000  5.809556      0.500000             0.0
71584           0.0  0.071280  5.802797      0.000000             0.0
47825           0.0  0.000000  5.590743      0.000000             0.0
12120           0.0  0.000000  5.886979      0.426401             0.0
13953           0.0  0.133254  5.777254      0.000000             0.0
71834           0.0  0.028090  5.548156      0.000000             1.0
46962           0.0  0.000000  6.335671      0.000000             0.0
23704           0.0  0.041026  6.011440      0.000000             0.0
29247           0.0  0.019026  4.363156      0.000000             0.0
7355            0.0  0.000000  5.908156      0.000000             0.0

       sim_title
74030   0.000000
76203   0.000000
14054   0.000000
13890   0.000000
61706   0.000000
29382   0.000000
14185   0.000000
53591   0.000000
4466    0.000000
46879   0.000000
13830   0.000000
71584   0.601196
47825   0.580683
12120   0.000000
13953   0.400904
71834   0.000000
46962   0.474825
23704   0.433409
29247   0.433409
7355    0.428964

Source Movie: These Glamour Girls
                                          title  sim_total  sim_director  \
13751  Bud Abbott and Lou Costello in Hollywood   0.930940           1.0

# Dynamic Weight system

In [81]:
# STEP 1: BUILD INVERTED INDICES (LOOKUP DICTIONARIES)

from collections import defaultdict
import pandas as pd
import numpy as np

def normalize_name(name):
    """
    Normalize names to handle multiple formats.
    'Christopher Nolan' -> 'christophernolan'
    'christopher nolan' -> 'christophernolan'
    'christophernolan' -> 'christophernolan'
    """
    if pd.isna(name) or not str(name).strip():
        return None
    return re.sub(r'\s+', '', str(name).lower().strip())

def build_lookup_indices(movies_df):
    """
    Build hash maps for fast categorical lookups.
    Returns dict of dicts: entity_type -> {entity_value: [movie_indices]}
    """

    # 1. Director Lookup
    director_lookup = defaultdict(list)
    for idx, director in enumerate(movies_df['director']):
        if pd.notna(director) and str(director).strip():
            # Store both original and lowercase for flexible matching
            director_lookup[str(director).lower().strip()].append(idx)

    # 2. Genre Lookup
    genre_lookup = defaultdict(list)
    for idx, genres in enumerate(movies_df['genres']):
        if isinstance(genres, list):
            for genre in genres:
                genre_lookup[str(genre).lower().strip()].append(idx)
        elif isinstance(genres, str) and genres:
            # Handle comma-separated string format
            for genre in genres.split(','):
                genre_lookup[genre.lower().strip()].append(idx)

    # 3. Keyword Lookup
    keyword_lookup = defaultdict(list)
    for idx, keywords in enumerate(movies_df['keywords']):
        if isinstance(keywords, list):
            for kw in keywords:
                keyword_lookup[str(kw).lower().strip()].append(idx)
        elif isinstance(keywords, str) and keywords:
            for kw in keywords.split(','):
                keyword_lookup[kw.lower().strip()].append(idx)

    # 4. Cast Lookup (top 5 actors per movie)
    cast_lookup = defaultdict(list)
    for idx, cast_list in enumerate(movies_df['cast']):
        if isinstance(cast_list, list):
            for actor in cast_list[:5]:
                cast_lookup[str(actor).lower().strip()].append(idx)
        elif isinstance(cast_list, str) and cast_list:
            for actor in cast_list.split(',')[:3]:
                cast_lookup[actor.lower().strip()].append(idx)

    # 5. Production Company Lookup
    production_lookup = defaultdict(list)
    for idx, companies in enumerate(movies_df['production_companies']):
        if isinstance(companies, list):
            for company in companies[:3]:
                production_lookup[str(company).lower().strip()].append(idx)
        elif isinstance(companies, str) and companies:
            for company in companies.split(',')[:1]:
                production_lookup[company.lower().strip()].append(idx)

    return {
        'director': dict(director_lookup),
        'genre': dict(genre_lookup),
        'keyword': dict(keyword_lookup),
        'cast': dict(cast_lookup),
        'production': dict(production_lookup)
    }

# BUILD THE LOOKUPS (run once)
lookups = build_lookup_indices(movies)

print("=== Lookup Statistics ===")
print(f"Unique Directors: {len(lookups['director']):,}")
print(f"Unique Genres: {len(lookups['genre']):,}")
print(f"Unique Keywords: {len(lookups['keyword']):,}")
print(f"Unique Actors: {len(lookups['cast']):,}")
print(f"Unique Production Companies: {len(lookups['production']):,}")

=== Lookup Statistics ===
Unique Directors: 34,175
Unique Genres: 19
Unique Keywords: 30,591
Unique Actors: 92,494
Unique Production Companies: 42,404

In [95]:
# STEP 1: BUILD OPTIMIZED INVERTED INDICES (LOOKUP DICTIONARIES)

import pandas as pd
import numpy as np
import re
from collections import defaultdict

def sanitize_key(text):
    """
    Converts input into a standardized 'soup' key.
    Examples:
    'Science Fiction' -> 'sciencefiction'
    'Christopher Nolan' -> 'christophernolan'
    '  Action ' -> 'action'
    """
    if pd.isna(text) or text == "":
        return None

    # Convert to string, lowercase, and remove ALL whitespace (not just trim)
    clean_text = str(text).lower()
    clean_text = re.sub(r'\s+', '', clean_text)

    return clean_text if clean_text else None

def build_lookup_indices(movies_df):
    """
    Builds hash maps mapping 'sanitized_key' -> [List of Movie Indices].
    This allows O(1) retrieval without scanning columns.
    """

    # Initialize dictionaries
    lookups = {
        'director': defaultdict(list),
        'genre': defaultdict(list),
        'keyword': defaultdict(list),
        'cast': defaultdict(list),
        'production': defaultdict(list)
    }

    # Iterate over the dataframe once (More efficient than column-wise processing)
    for idx, row in movies_df.iterrows():

        # 1. Director Lookup
        d_key = sanitize_key(row['director'])
        if d_key:
            lookups['director'][d_key].append(idx)

        # 2. Genre Lookup (Handle lists or strings)
        genres = row['genres']
        if isinstance(genres, list):
            for g in genres:
                g_key = sanitize_key(g)
                if g_key: lookups['genre'][g_key].append(idx)
        elif isinstance(genres, str):
            # Fallback for string representations like "Action, Comedy"
            for g in genres.split(','):
                g_key = sanitize_key(g)
                if g_key: lookups['genre'][g_key].append(idx)

        # 3. Keyword Lookup
        keywords = row['keywords']
        if isinstance(keywords, list):
            for k in keywords:
                k_key = sanitize_key(k)
                if k_key: lookups['keyword'][k_key].append(idx)

        # 4. Cast Lookup (Limit to top 5 to reduce noise)
        cast = row['cast']
        if isinstance(cast, list):
            for actor in cast[:5]:
                a_key = sanitize_key(actor)
                if a_key: lookups['cast'][a_key].append(idx)

        # 5. Production Company Lookup (Limit to top 3)
        companies = row['production_companies']
        if isinstance(companies, list):
            for c in companies[:3]:
                c_key = sanitize_key(c)
                if c_key: lookups['production'][c_key].append(idx)

    # Convert defaultdicts to standard dicts for cleaner printing/usage
    return {k: dict(v) for k, v in lookups.items()}

# ---------------------------------------------------------
# EXECUTE BUILD
# ---------------------------------------------------------
print("Building Inverted Indices...")
lookups = build_lookup_indices(movies)

print("\n=== Lookup Statistics (Nodes in Graph) ===")
print(f"Unique Directors:  {len(lookups['director']):,}")
print(f"Unique Genres:     {len(lookups['genre']):,}")
print(f"Unique Keywords:   {len(lookups['keyword']):,}")
print(f"Unique Actors:     {len(lookups['cast']):,}")
print(f"Unique Companies:  {len(lookups['production']):,}")

Building Inverted Indices...

=== Lookup Statistics (Nodes in Graph) ===
Unique Directors:  34,175
Unique Genres:     19
Unique Keywords:   30,408
Unique Actors:     92,494
Unique Companies:  42,248

[Verification] Found 5395 movies for 'sciencefiction'

In [96]:
# Verification Test
test_director = "sciencefiction"
if test_director in lookups['genre']:
    print(f"\n[Verification] Found {len(lookups['genre'][test_director])} movies for '{test_director}'")
else:
    print(f"\n[Verification] '{test_director}' not found (Check sanitization logic)")

[Verification] Found 5395 movies for 'sciencefiction'

In [97]:
# DYNAMIC WEIGHT CALCULATOR

def calculate_dynamic_weights(movie=None, director=None, genres=None,
                               keywords=None, actor=None):
    """
    Dynamically calculate weights based on provided inputs.

    Logic:
    - More inputs = distribute weights across them
    - If seed movie provided = movie similarity gets higher base weight
    - If only attributes (no movie) = attributes share the weight pool
    """

    # Count active inputs
    active_inputs = []
    if movie: active_inputs.append('movie')
    if director: active_inputs.append('director')
    if genres: active_inputs.append('genre')
    if keywords: active_inputs.append('keyword')
    if actor: active_inputs.append('actor')

    num_active = len(active_inputs)

    if num_active == 0:
        return None, "No inputs provided"

        # {This should give the current popular movies instead of nothing}

    # Base weight distribution
    weights = {
        'movie': 0.5,
        'director': 0.7,
        'genre': 0.6,
        'keyword': 0.6,
        'actor': 0.1
    }

    # WEIGHT ASSIGNMENT LOGIC

    if num_active == 1:
        # Single input gets full weight
        weights[active_inputs[0]] = 1.0

    elif movie and num_active == 2:
        # Movie + 1 attribute: Movie dominant
        weights['movie'] = 0.6
        other = [x for x in active_inputs if x != 'movie'][0]
        weights[other] = 0.4

    elif movie and num_active >= 3:
        # Movie + multiple attributes: Movie still important but shared
        weights['movie'] = 0.4
        remaining = 0.6
        others = [x for x in active_inputs if x != 'movie']
        per_other = remaining / len(others)
        for o in others:
            weights[o] = per_other

    else:
        # No movie (pure attribute search): Equal distribution with genre boost
        base_weight = 1.0 / num_active
        for inp in active_inputs:
            weights[inp] = base_weight
        # Slightly boost director if present
        if 'director' in active_inputs:
            weights['director'] *= 1.3
            # Renormalize
            total = sum(weights.values())
            weights = {k: v/total for k, v in weights.items()}

    return weights, active_inputs

# Test the weight calculator
test_cases = [
    {'movie': 'Interstellar'},
    {'movie': 'Interstellar', 'director': 'christophernolan'},
    {'director': 'christophernolan', 'genres': ['Thriller']},
    {'movie': 'Inception', 'genres': ['Sci-Fi'], 'keywords': ['dream', 'heist']},
]

print("=== Dynamic Weight Tests ===")
for tc in test_cases:
    w, active = calculate_dynamic_weights(**tc)
    print(f"Input: {tc}")
    print(f"  Weights: {w}")
    print()

=== Dynamic Weight Tests ===
Input: {'movie': 'Interstellar'}
  Weights: {'movie': 1.0, 'director': 0.7, 'genre': 0.6, 'keyword': 0.6, 'actor': 0.1}

Input: {'movie': 'Interstellar', 'director': 'christophernolan'}
  Weights: {'movie': 0.6, 'director': 0.4, 'genre': 0.6, 'keyword': 0.6, 'actor': 0.1}

Input: {'director': 'christophernolan', 'genres': ['Thriller']}
  Weights: {'movie': 0.2127659574468085, 'director': 0.2765957446808511, 'genre': 0.2127659574468085, 'keyword': 0.2553191489361702, 'actor': 0.0425531914893617}

Input: {'movie': 'Inception', 'genres': ['Sci-Fi'], 'keywords': ['dream', 'heist']}
  Weights: {'movie': 0.4, 'director': 0.7, 'genre': 0.3, 'keyword': 0.3, 'actor': 0.1}

In [98]:
# UNIFIED SCORING ENGINE

from sklearn.metrics.pairwise import cosine_similarity

def compute_dynamic_scores(
    movies_df,
    indices,
    mat_desc,
    lookups,
    movie=None,
    director=None,
    genres=None,
    keywords=None,
    actor=None,
    custom_weights=None
):
    """
    Compute scores for all movies based on provided inputs.

    Returns:
        np.array of scores for each movie (shape: num_movies,)
    """

    num_movies = len(movies_df)
    total_scores = np.zeros(num_movies)

    # Get weights
    if custom_weights:
        weights = custom_weights
    else:
        weights, active_inputs = calculate_dynamic_weights(
            movie=movie, director=director, genres=genres,
            keywords=keywords, actor=actor
        )
        if weights is None:
            return total_scores

    seed_idx = None

    # MOVIE SIMILARITY
    if movie and weights.get('movie', 0) > 0:
        if movie in indices:
            seed_idx = indices[movie]

            # Handle duplicate titles
            if isinstance(seed_idx, (pd.Series, pd.Index, np.ndarray, list)):
                seed_idx = seed_idx.iloc[0] if hasattr(seed_idx, 'iloc') else seed_idx[0]

            # Cosine similarity against all movies
            sim_scores = cosine_similarity(
                mat_desc[seed_idx],
                mat_desc
            ).flatten()

            total_scores += sim_scores * weights['movie']
        else:
            print(f"Warning: Movie '{movie}' not found in index")

    # DIRECTOR BOOST (Sparse)
    if director and weights.get('director', 0) > 0:
        director_key = director.lower().strip()
        director_key = normalize_name(director_key)
        target_indices = lookups['director'].get(director_key, [])

        if target_indices:
            # Boost all movies by this director
            total_scores[target_indices] += weights['director']
        else:
            print(f"Warning: Director '{director}' not found in lookup")

    # GENRE BOOST (Sparse)
    if genres and weights.get('genre', 0) > 0:
        if isinstance(genres, str):
            genres = [genres]

        genre_weight_per = weights['genre'] / len(genres)

        for genre in genres:
            genre_key = genre.lower().strip()
            genre_key = normalize_name(genre_key)
            target_indices = lookups['genre'].get(genre_key, [])

            if target_indices:
                total_scores[target_indices] += genre_weight_per

    # KEYWORD BOOST (Sparse)
    if keywords and weights.get('keyword', 0) > 0:
        if isinstance(keywords, str):
            keywords = [keywords]

        keyword_weight_per = weights['keyword'] / len(keywords)

        for kw in keywords:
            kw_key = kw.lower().strip()
            kw_key = normalize_name(kw_key)
            target_indices = lookups['keyword'].get(kw_key, [])

            if target_indices:
                total_scores[target_indices] += keyword_weight_per

    # ACTOR BOOST (Sparse)
    if actor and weights.get('actor', 0) > 0:
        actor_key = actor.lower().strip()
        actor_key = normalize_name(actor_key)
        target_indices = lookups['cast'].get(actor_key, [])

        if target_indices:
            total_scores[target_indices] += weights['actor']

    return total_scores, seed_idx, weights

In [99]:
# MAIN RECOMMENDATION FUNCTION

def get_dynamic_recommendations(
    movies_df,
    indices,
    mat_desc,
    lookups,
    movie=None,
    director=None,
    genres=None,
    keywords=None,
    actor=None,
    custom_weights=None,
    top_n=15,
    min_votes=None,
    verbose=True
):
    """
    Get movie recommendations based on any combination of inputs.

    Parameters:
    -----------
    movies_df : pd.DataFrame
        Your movies dataframe
    indices : pd.Series
        Title to index mapping
    mat_desc : sparse matrix
        TF-IDF matrix for descriptions
    lookups : dict
        Inverted indices from build_lookup_indices()
    movie : str, optional
        Seed movie title for similarity
    director : str, optional
        Director name to boost
    genres : list or str, optional
        Genre(s) to boost
    keywords : list or str, optional
        Keyword(s) to boost
    actor : str, optional
        Actor name to boost
    custom_weights : dict, optional
        Override automatic weights
    top_n : int
        Number of recommendations to return
    min_votes : int, optional
        Minimum vote count filter
    verbose : bool
        Print debug information

    Returns:
    --------
    pd.DataFrame with recommendations
    """

    # Compute scores
    scores, seed_idx, weights = compute_dynamic_scores(
        movies_df=movies_df,
        indices=indices,
        mat_desc=mat_desc,
        lookups=lookups,
        movie=movie,
        director=director,
        genres=genres,
        keywords=keywords,
        actor=actor,
        custom_weights=custom_weights
    )

    if verbose:
        print(f"Inputs:")
        if movie: print(f"  Movie: {movie}")
        if director: print(f"  Director: {director}")
        if genres: print(f"  Genres: {genres}")
        if keywords: print(f"  Keywords: {keywords}")
        if actor: print(f"  Actor: {actor}")
        print(f"\nCalculated Weights:")
        for k, v in weights.items():
            if v > 0:
                print(f"  {k}: {v:.3f}")
        print("-" * 60)

    # Get top candidates (more than needed for filtering)
    candidate_pool = min(top_n * 3, len(movies_df))
    top_indices = np.argsort(scores)[::-1][:candidate_pool]

    # Build results DataFrame
    result_cols = ['title', 'director', 'genres', 'keywords',
                   'voteaverage', 'votecount', 'year']
    available_cols = [c for c in result_cols if c in movies_df.columns]

    results = movies_df.iloc[top_indices][available_cols].copy()
    results['score'] = scores[top_indices]

    # Exclude seed movie if provided
    if seed_idx is not None:
        results = results[results.index != seed_idx]

    # Apply minimum votes filter
    if min_votes and 'votecount' in results.columns:
        results = results[results['votecount'] >= min_votes]

    # Calculate weighted rating (your existing formula)
    if 'voteaverage' in results.columns and 'votecount' in results.columns:
        C = results['voteaverage'].mean()
        m = results['votecount'].quantile(0.25)

        def weighted_rating(x, m=m, C=C):
            v = x['votecount']
            R = x['voteaverage']
            return (v / (v + m) * R) + (m / (v + m) * C)

        results['wr_score'] = results.apply(weighted_rating, axis=1)

    results = results.head(top_n)

    if verbose:
        print(f"Returning {len(results)} recommendations")

    return results

In [100]:
# TEST THE SYSTEM

print("Movie Only (like your original system)")
recs1 = get_dynamic_recommendations(
    movies_df=movies,
    indices=indices,
    mat_desc=mat_desc,
    lookups=lookups,
    movie='Interstellar',
    top_n=10
)
print(recs1[['title', 'director', 'score']].to_string())


print("TEST 2: Movie + Director")
print("="*70)
recs2 = get_dynamic_recommendations(
    movies_df=movies,
    indices=indices,
    mat_desc=mat_desc,
    lookups=lookups,
    movie='Interstellar',
    director='Christopher Nolan',
    top_n=10
)
print(recs2[['title', 'director', 'score']].to_string())


print("TEST 3: Movie + Genre (Interstellar but Thriller)")
print("="*70)
recs3 = get_dynamic_recommendations(
    movies_df=movies,
    indices=indices,
    mat_desc=mat_desc,
    lookups=lookups,
    movie='Interstellar',
    genres=['Thriller'],
    top_n=10
)
print(recs3[['title', 'genres', 'score']].to_string())


print("TEST 4: Director + Genre Only (No Seed Movie)")
recs4 = get_dynamic_recommendations(
    movies_df=movies,
    indices=indices,
    mat_desc=mat_desc,
    lookups=lookups,
    director='David Fincher',
    genres=['Thriller'],
    top_n=10
)
print(recs4[['title', 'director', 'genres', 'score']].to_string())


print("TEST 5: Movie + Multiple Attributes")
recs5 = get_dynamic_recommendations(
    movies_df=movies,
    indices=indices,
    mat_desc=mat_desc,
    lookups=lookups,
    movie='The Dark Knight',
    director='Christopher Nolan',
    genres=['Action', 'Crime'],
    keywords=['superhero', 'vigilante'],
    top_n=10
)
print(recs5[['title', 'director', 'score']].to_string())


print("TEST 6: Keywords Only (Concept Search)")
recs6 = get_dynamic_recommendations(
    movies_df=movies,
    indices=indices,
    mat_desc=mat_desc,
    lookups=lookups,
    keywords=['space', 'astronaut', 'survival'],
    top_n=10
)
print(recs6[['title', 'keywords', 'score']].to_string())


print("TEST 7: Custom Weights Override")
# custom = {
#     'movie': 0.1,
#     'director': 0.1,
#     'genre': 0.1,
#     'keyword': 0.1,
#     'actor': 0.0
# }
recs7 = get_dynamic_recommendations(
    movies_df=movies,
    indices=indices,
    mat_desc=mat_desc,
    lookups=lookups,
    movie='Inception',
    director='David Fincher',
    genres=['Science Fiction'],
    top_n=10
)
print(recs7[['title', 'director', 'score']].to_string())

Movie Only (like your original system)
Inputs:
  Movie: Interstellar

Calculated Weights:
  movie: 1.000
  director: 0.700
  genre: 0.600
  keyword: 0.600
  actor: 0.100
------------------------------------------------------------
Returning 10 recommendations
                      title           director     score
51230            The Beyond       hasrafdulull  0.225105
18003            Prometheus        ridleyscott  0.174830
80155                Origin      davidparrella  0.168225
75889                Within  olatundeosunsanmi  0.165968
54283     A Species Odyssey   jacquesmalaterre  0.155566
80011         The Prototype       marcelogrion  0.151959
37366  AE: Apocalypse Earth       thunderlevin  0.151832
42678     Voyage to the Sky       jeanpainlevé  0.150714
47766           Anti Matter        keirburrows  0.144483
59010               Genesis        osamutezuka  0.143837
TEST 2: Movie + Director
======================================================================
Inputs:
  Movie: Interstellar
  Director: Christopher Nolan

Calculated Weights:
  movie: 0.600
  director: 0.400
  genre: 0.600
  keyword: 0.600
  actor: 0.100
------------------------------------------------------------
Returning 10 recommendations
                       title          director  score
17346  The Dark Knight Rises  christophernolan    0.4
66470                  Tenet  christophernolan    0.4
4102                 Memento  christophernolan    0.4
2471               Following  christophernolan    0.4
5258                Insomnia  christophernolan    0.4
84910            Oppenheimer  christophernolan    0.4
9960           Batman Begins  christophernolan    0.4
11115           The Prestige  christophernolan    0.4
47062                Dunkirk  christophernolan    0.4
12165        The Dark Knight  christophernolan    0.4
TEST 3: Movie + Genre (Interstellar but Thriller)
======================================================================
Inputs:
  Movie: Interstellar
  Genres: ['Thriller']

Calculated Weights:
  movie: 0.600
  director: 0.700
  genre: 0.400
  keyword: 0.600
  actor: 0.100
------------------------------------------------------------
Returning 10 recommendations
                               title                                       genres     score
75889                         Within                    [Drama, Horror, Thriller]  0.499581
80011                  The Prototype          [Action, Science Fiction, Thriller]  0.491176
54216                          Astro          [Science Fiction, Action, Thriller]  0.482382
1213   The Day the Earth Stood Still           [Science Fiction, Thriller, Drama]  0.477881
69178                  Minor Premise           [Science Fiction, Thriller, Drama]  0.468721
27993                      Alienator  [Action, Science Fiction, Thriller, Horror]  0.466668
74641     A Mother of No Destination                  [Science Fiction, Thriller]  0.463256
57857                    Escape Room                  [Horror, Thriller, Mystery]  0.461643
51996                  The Body Tree                           [Thriller, Horror]  0.460943
60936                         Frenzy                 [Horror, Thriller, TV Movie]  0.458331
TEST 4: Director + Genre Only (No Seed Movie)
Inputs:
  Director: David Fincher
  Genres: ['Thriller']

Calculated Weights:
  movie: 0.213
  director: 0.277
  genre: 0.213
  keyword: 0.255
  actor: 0.043
------------------------------------------------------------
Returning 10 recommendations
                                     title      director                      genres     score
17386      The Girl with the Dragon Tattoo  davidfincher  [Thriller, Crime, Mystery]  0.489362
5136                            Panic Room  davidfincher    [Crime, Drama, Thriller]  0.489362
11385                               Zodiac  davidfincher  [Crime, Mystery, Thriller]  0.489362
2848                            Fight Club  davidfincher           [Drama, Thriller]  0.489362
46                                   Se7en  davidfincher  [Crime, Mystery, Thriller]  0.489362
1556                              The Game  davidfincher  [Drama, Thriller, Mystery]  0.489362
21636                            Gone Girl  davidfincher  [Mystery, Thriller, Drama]  0.489362
69176                                 Mank  davidfincher            [Drama, History]  0.276596
15139                   The Social Network  davidfincher                     [Drama]  0.276596
12841  The Curious Case of Benjamin Button  davidfincher   [Drama, Fantasy, Romance]  0.276596
TEST 5: Movie + Multiple Attributes
Inputs:
  Movie: The Dark Knight
  Director: Christopher Nolan
  Genres: ['Action', 'Crime']
  Keywords: ['superhero', 'vigilante']

Calculated Weights:
  movie: 0.400
  director: 0.200
  genre: 0.200
  keyword: 0.200
  actor: 0.100
------------------------------------------------------------
Returning 10 recommendations
                                                                      title           director     score
17346                                                 The Dark Knight Rises   christophernolan  0.730355
9960                                                          Batman Begins   christophernolan  0.665113
584                                                                  Batman          timburton  0.506399
75187                                  Batman: The Long Halloween, Part One        chrispalmer  0.428199
75720                                  Batman: The Long Halloween, Part Two        chrispalmer  0.425808
63577  Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)           cathyyan  0.412203
3446                                                    The Crow: Salvation      bharatnalluri  0.409486
4510                                                           The Punisher      markgoldblatt  0.402567
151                                                          Batman Forever     joelschumacher  0.401184
7275                                                           The Punisher  jonathanhensleigh  0.400000
TEST 6: Keywords Only (Concept Search)
Inputs:
  Keywords: ['space', 'astronaut', 'survival']

Calculated Weights:
  movie: 0.500
  director: 0.700
  genre: 0.600
  keyword: 1.000
  actor: 0.100
------------------------------------------------------------
Returning 10 recommendations
                                               title                                                                                                                                                                                                                                                                                                                                             keywords     score
85594                                       The Moon                                                                                                                                                                                                                                                 [moon, isolation, survival, space, stranded, astronaut, struggle for survival, duringcreditsstinger]  1.000000
29327                                    The Martian                                                                                                    [spacecraft, planet mars, based on novel or book, nasa, isolation, botanist, alone, survival, space, engineering, stranded, astronaut, struggle for survival, duringcreditsstinger, deep space, potatoes, 2030s, faithful adaptation, optimistic]  1.000000
148                                        Apollo 13                                                                                                                                    [rescue, florida, race against time, moon, nasa, spaceman, based on true story, houston, texas, survival, space, disaster, explosion, astronaut, hypothermia, apollo program, lunar mission, spacecraft accident]  1.000000
77888  The Wonderful: Stories from the Space Station                                                                                                                                                                                                                                                                                                [space, astronaut, international space station (iss)]  0.666667
74066                                       Stowaway                                                                                                                                                                                                                                                                                                    [space travel, space, astronaut, space adventure]  0.666667
1814                                      Armageddon     [daughter, race against time, space marine, moon, washington dc, usa, saving the world, cataclysm, paris, france, asteroid, self sacrifice, nasa, loss of loved one, natural disaster, u.s. air force, end of the world, space, disaster, wedding, astronaut, duringcreditsstinger, disaster movie, heroic mission, daring rescue, space centre]  0.666667
1580                                         Gattaca  [genetics, cheating, paraplegic, suicide attempt, dystopia, dna, new identity, investigation, heart disease, spaceman, fraud, space travel, fake identity, in vitro fertilisation, biotechnology, space mission, space, astronaut, swimming, exercise, eugenics, murder investigation, discrimination, brother brother relationship, authoritarian]  0.666667
77571                                   Moonwalk One                                                                                                                                                                  [nasa, space, astronaut, archive footage, moon walk, old footage, apollo program, history of mankind, history and legacy, space vessel, found footage film, historical documentary]  0.666667
11355                           First Man into Space                                                                                                                                                                                                                                                      [monster, mutant, space travel, rocket, space, b movie, black and white, astronaut, test pilot]  0.666667
5745                                         Solaris                                                                                                                                                                   [loss of sense of reality, based on novel or book, loss of loved one, clone, hallucination, space travel, grief, space, psychologist, astronaut, space station, unusual phenomena]  0.666667
TEST 7: Custom Weights Override
Inputs:
  Movie: Inception
  Director: David Fincher
  Genres: ['Science Fiction']

Calculated Weights:
  movie: 0.400
  director: 0.300
  genre: 0.300
  keyword: 0.600
  actor: 0.100
------------------------------------------------------------
Returning 10 recommendations
                       title           director     score
1278                  Alien³       davidfincher  0.600000
38096         Straight Story         efimouriki  0.340084
44827             Major Grom    vladimirbesedin  0.339951
44357             MindGamers         andrewgoth  0.339108
7454                  Cypher     vincenzonatali  0.337941
33880                Control          kennethbi  0.337752
10697            Renaissance  christianvolckman  0.334321
26066  The Fountain of Youth        orsonwelles  0.332645
38607         The Flying Man     marcusalqueres  0.331537
66272              Possessor  brandoncronenberg  0.330852

In [102]:
# MINIMAL SETUP

# 1. Build lookups (run once after data loading)
lookups = build_lookup_indices(movies)

# 2. Get recommendations (call anytime)
recommendations = get_dynamic_recommendations(
    movies_df=movies,
    indices=indices,
    mat_desc=mat_desc,
    lookups=lookups,
    movie='Interstellar',
    director='Christopher Nolan',
    genres=['Science Fiction', 'romance'],
    keywords=['space', 'time'],
    top_n=15
)

recommendations

Inputs:
  Movie: Interstellar
  Director: Christopher Nolan
  Genres: ['Science Fiction', 'romance']
  Keywords: ['space', 'time']

Calculated Weights:
  movie: 0.400
  director: 0.200
  genre: 0.200
  keyword: 0.200
  actor: 0.100
------------------------------------------------------------
Returning 15 recommendations

,title,director,genres,keywords,year,score
1580,Gattaca,andrewniccol,"[Thriller, Science Fiction, Mystery, Romance]","[genetics, cheating, paraplegic, suicide attem...",1997.0,0.324552
4848,Vanilla Sky,cameroncrowe,"[Mystery, Romance, Science Fiction]","[regret, jealousy, amnesia, dreams, love of on...",2001.0,0.300000
66470,Tenet,christophernolan,"[Action, Thriller, Science Fiction]","[assassin, espionage, spy, time travel, mumbai...",2020.0,0.300000
11115,The Prestige,christophernolan,"[Drama, Mystery, Science Fiction]","[dying and death, suicide, class society, lond...",2006.0,0.300000
12364,Doctor Who,geoffreysax,"[TV Movie, Adventure, Science Fiction]","[clock, time travel, time, space, millennium, ...",1996.0,0.300000
14888,Mr. Nobody,jacovandormael,"[Science Fiction, Drama, Romance]","[time travel, surrealism, time, choice, free w...",2009.0,0.300000
14844,Inception,christophernolan,"[Action, Science Fiction, Adventure]","[rescue, mission, dreams, airplane, paris, fra...",2010.0,0.300000
43598,Passengers,mortentyldum,"[Drama, Romance, Science Fiction]","[android, spacecraft, asteroid, isolation, sho...",2016.0,0.300000
47952,Nude on the Moon,doriswishman,"[Comedy, Fantasy, Romance, Science Fiction]","[moon, exploitation, space, nudism, woman dire...",1961.0,0.300000
45309,Space Mutiny,nealsundstrom,"[Romance, Adventure, Science Fiction]","[spacecraft, dancing, mutiny, corruption, rock...",1988.0,0.300000
80970,Press Play,gregbjörkman,"[Music, Romance, Science Fiction]","[time travel, time, destiny, music]",2022.0,0.300000
32342,Ditto,kimjeong-kwon,"[Drama, Fantasy, Romance, Science Fiction]","[1970s, radio, interview, time, campus, walkie...",2000.0,0.300000
82788,Crest of the Stars: Birth,osamunabeshima,"[Science Fiction, Romance, Animation]","[space, military]",2000.0,0.300000
18003,Prometheus,ridleyscott,"[Science Fiction, Adventure, Mystery]","[android, alien, space, creature, spin off, cr...",2012.0,0.269932
12732,Critters 4,rupertharvey,"[Comedy, Horror, Science Fiction]","[future, shower, hologram, alien, space, creat...",1992.0,0.253814

PIPELINE FUNCTION - END IO

In [103]:
import numpy as np

class InteractiveRecommender:
    def __init__(self, movies_df, indices, mat_desc, lookups):
        self.movies = movies_df
        self.indices = indices
        self.mat_desc = mat_desc
        self.lookups = lookups
        self.user_profile = None
        self.profile_keywords = set()

    def build_user_profile(self):
        """
        Step 1: Ingest User Favorites to build a 'Taste Vector'
        """
        print("\n--- STEP 1: TELL ME WHAT YOU LOVE ---")

        # 1. Inputs (Simulated text inputs for notebook)
        print("Enter 3 Favorite Movies (exact titles):")
        fav_movies = [input(f"Movie {i+1}: ").strip() for i in range(3)]

        print("\nEnter 2 Favorite Directors:")
        fav_directors = [input(f"Director {i+1}: ").strip() for i in range(2)]

        print("\nEnter 2 Favorite Genres:")
        fav_genres = [input(f"Genre {i+1}: ").strip() for i in range(2)]

        # 2. Construct the Profile Vector (Aggregation Strategy)
        # We start with a zero vector and add the vectors of all favorites
        profile_vector = np.zeros(self.mat_desc.shape[1]) # TF-IDF shape
        valid_inputs = 0

        # Add Movie Plot Vectors
        for m in fav_movies:
            if m in self.indices:
                idx = self.indices[m]
                # In a real app, we'd use dense vectors. Here we use the TF-IDF row.
                # Note: Sparse matrix addition is slow-ish but fine for 3 items.
                profile_vector += self.mat_desc[idx].toarray()[0]
                valid_inputs += 1

                # Collect keywords for metadata matching
                kws = self.movies.at[idx, 'keywords']
                if isinstance(kws, list):
                    self.profile_keywords.update(kws)

        # We also collect the 'Taste' tags from Directors/Genres for later boosting
        self.profile_tags = {
            'directors': [d.lower().replace(" ", "") for d in fav_directors if d],
            'genres': [g.lower().replace(" ", "") for g in fav_genres if g]
        }

        # Normalize the profile vector
        if valid_inputs > 0:
            profile_vector /= valid_inputs
            self.user_profile = profile_vector
            print("\n✅ Profile Built! I have analyzed your taste.")
        else:
            print("\n⚠️ Could not find those movies. Profile is empty.")

    def get_session_recommendations(self):
        """
        Step 2: Ask for Current Mood and Recommend
        """
        if self.user_profile is None:
            print("Please build a profile first!")
            return

        print("\n--- STEP 2: WHAT ARE YOU WATCHING NOW? ---")
        query_movie = input("Reference Movie (leave blank if none): ").strip()
        query_keywords = input("Keywords/Mood (e.g., 'dark space travel'): ").strip()

        # --- SCORING LOGIC ---

        # 1. Base Score (The Current Query)
        # This is the "King". We calculate this first.
        # We assume 'get_dynamic_recommendations' returns raw scores/indices internally
        # For this demo, we will calculate raw scores manually here

        total_scores = np.zeros(len(self.movies))

        # A. Query Movie Score
        if query_movie and query_movie in self.indices:
            idx = self.indices[query_movie]
            sim_scores = cosine_similarity(self.mat_desc[idx], self.mat_desc).flatten()
            total_scores += sim_scores * 1.0 # High weight for explicit request

        # B. Keyword/Mood Score (TF-IDF transformation of query)
        if query_keywords:
            # Transform user query into vector space
            query_vec = tfidf.transform([query_keywords])
            kw_scores = cosine_similarity(query_vec, self.mat_desc).flatten()
            total_scores += kw_scores * 0.8

        # 2. Personalization Boost (The "Match" Logic)
        # We only apply the profile boost if it makes sense.

        # Calculate alignment between Profile and Current Query
        # (Simplified: Do keywords overlap?)
        query_tokens = set(query_keywords.lower().split())
        overlap = query_tokens.intersection(self.profile_keywords)

        personalization_weight = 0.0
        if len(overlap) > 0 or query_movie:
            print(f"   -> Match found with your profile (Overlap: {overlap})! Personalizing results...")
            personalization_weight = 0.3
        else:
            print("   -> No clear overlap with your history. Prioritizing current query.")
            personalization_weight = 0.05 # Tiny bias just to tie-break

        # Apply Profile Vector similarity
        profile_sim = cosine_similarity(self.user_profile.reshape(1, -1), self.mat_desc).flatten()
        total_scores += profile_sim * personalization_weight

        # Apply Profile Directors/Genres boost (if applicable)
        for d in self.profile_tags['directors']:
            if d in self.lookups['director']:
                # Smaller boost than a direct query match
                total_scores[self.lookups['director'][d]] += 0.2

        # 3. Final Sort & Display
        top_indices = np.argsort(total_scores)[::-1][:25]
        results = self.movies.iloc[top_indices][['title', 'vote_average', 'director', 'genres']]
        results['match_score'] = total_scores[top_indices]

        return results

# --- HOW TO RUN ---
# 1. Initialize
app = InteractiveRecommender(movies, indices, tfidf_matrix, lookups)

# 2. Build Profile (User types inputs)
app.build_user_profile()

# 3. Get Recommendations
recs = app.get_session_recommendations()
print("\n=== YOUR PERSONALIZED PICKS ===")
print(recs)

--- STEP 1: TELL ME WHAT YOU LOVE ---
Enter 3 Favorite Movies (exact titles):
Movie 1: The Dark Knight Rises
Movie 2: Interstellar
Movie 3: A Beautiful Mind

Enter 2 Favorite Directors:
Director 1: Christopher Nolan
Director 2: David Fincher

Enter 2 Favorite Genres:
Genre 1: Science Fiction
Genre 2: Thriller

✅ Profile Built! I have analyzed your taste.

--- STEP 2: WHAT ARE YOU WATCHING NOW? ---
Reference Movie (leave blank if none): Thriller
Keywords/Mood (e.g., 'dark space travel'): Dark
   -> Match found with your profile (Overlap: set())! Personalizing results...

=== YOUR PERSONALIZED PICKS ===
                                     title  vote_average          director  \
59629                             Thriller         4.319     dallasjackson
17346                The Dark Knight Rises         7.789  christophernolan
20984                         Interstellar         8.463  christophernolan
46                                   Se7en         8.377      davidfincher
12165                      The Dark Knight         8.524  christophernolan
74924                          Happy Times         5.400      michaelmayer
9960                         Batman Begins         7.700  christophernolan
11385                               Zodiac         7.526      davidfincher
5258                              Insomnia         6.956  christophernolan
12841  The Curious Case of Benjamin Button         7.595      davidfincher

                                    genres  match_score
59629                    [Horror, Mystery]     1.000497
17346     [Action, Crime, Drama, Thriller]     0.421091
20984  [Adventure, Drama, Science Fiction]     0.373064
46              [Crime, Mystery, Thriller]     0.260305
12165     [Drama, Action, Crime, Thriller]     0.228694
74924                     [Comedy, Horror]     0.225627
9960                [Drama, Crime, Action]     0.214079
11385           [Crime, Mystery, Thriller]     0.209778
5258              [Thriller, Crime, Drama]     0.209473
12841            [Drama, Fantasy, Romance]     0.206335

In [104]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

class InteractiveRecommender:
    def __init__(self, movies_df, indices, mat_desc, lookups):
        self.movies = movies_df
        self.indices = indices
        self.mat_desc = mat_desc
        self.lookups = lookups

        # State
        self.user_profile = None
        self.profile_keywords = set()
        self.profile_tags = {}
        self.fav_indices = set() # NEW: Track what user already knows/likes

    def build_user_profile(self):
        """
        Step 1: Ingest User Favorites to build a 'Taste Vector'
        """
        print("\n--- STEP 1: TELL ME WHAT YOU LOVE ---")

        # 1. Inputs (Simulated)
        print("Enter 3 Favorite Movies (exact titles):")
        fav_movies = [input(f"Movie {i+1}: ").strip() for i in range(3)]

        print("\nEnter 2 Favorite Directors:")
        fav_directors = [input(f"Director {i+1}: ").strip() for i in range(2)]

        print("\nEnter 2 Favorite Genres:")
        fav_genres = [input(f"Genre {i+1}: ").strip() for i in range(2)]

        # 2. Construct the Profile Vector
        profile_vector = np.zeros(self.mat_desc.shape[1])
        valid_inputs = 0

        # Reset favorites list
        self.fav_indices = set()

        for m in fav_movies:
            if m in self.indices:
                idx = self.indices[m]

                # Add to vector
                profile_vector += self.mat_desc[idx].toarray()[0]
                valid_inputs += 1

                # NEW: Add to exclusion list so we don't recommend it back
                self.fav_indices.add(idx)

                # Collect keywords
                kws = self.movies.at[idx, 'keywords']
                if isinstance(kws, list):
                    self.profile_keywords.update(kws)

        self.profile_tags = {
            'directors': [d.lower().replace(" ", "") for d in fav_directors if d],
            'genres': [g.lower().replace(" ", "") for g in fav_genres if g]
        }

        if valid_inputs > 0:
            profile_vector /= valid_inputs
            self.user_profile = profile_vector
            print(f"\n✅ Profile Built based on {valid_inputs} movies.")
        else:
            print("\n⚠️ Could not find those movies. Profile is empty.")

    def get_session_recommendations(self):
        """
        Step 2: Ask for Current Mood and Recommend (Filtering Favorites)
        """
        if self.user_profile is None:
            print("Please build a profile first!")
            return

        print("\n--- STEP 2: WHAT ARE YOU WATCHING NOW? ---")
        query_movie = input("Reference Movie (leave blank if none): ").strip()
        query_keywords = input("Keywords/Mood (e.g., 'dark space travel'): ").strip()

        # --- SCORING LOGIC ---
        total_scores = np.zeros(len(self.movies))

        # Track exclusions for this specific search
        current_exclusions = self.fav_indices.copy()

        # 1. Base Score (The Current Query)
        if query_movie and query_movie in self.indices:
            idx = self.indices[query_movie]
            sim_scores = cosine_similarity(self.mat_desc[idx], self.mat_desc).flatten()
            total_scores += sim_scores * 1.0
            current_exclusions.add(idx) # Don't recommend the reference movie itself

        if query_keywords:
            query_vec = tfidf.transform([query_keywords])
            kw_scores = cosine_similarity(query_vec, self.mat_desc).flatten()
            total_scores += kw_scores * 0.8

        # 2. Personalization Boost
        query_tokens = set(query_keywords.lower().split())
        overlap = query_tokens.intersection(self.profile_keywords)

        personalization_weight = 0.0
        if len(overlap) > 0 or query_movie:
            print(f"   -> Match found with profile! Personalizing...")
            personalization_weight = 0.3
        else:
            print("   -> Exploration Mode (Low profile bias).")
            personalization_weight = 0.05

        # Apply Profile Vector similarity
        profile_sim = cosine_similarity(self.user_profile.reshape(1, -1), self.mat_desc).flatten()
        total_scores += profile_sim * personalization_weight

        # Apply Profile Directors/Genres boost
        for d in self.profile_tags['directors']:
            if d in self.lookups['director']:
                total_scores[self.lookups['director'][d]] += 0.2

        # 3. Final Sort & Filter
        # Sort ALL movies first
        top_indices = np.argsort(total_scores)[::-1]

        # Filter out exclusions (Favorites + Current Seed)
        final_indices = [i for i in top_indices if i not in current_exclusions]

        # NEW: Return top 25 instead of 10
        top_25_indices = final_indices[:25]

        results = self.movies.iloc[top_25_indices][['title', 'vote_average', 'director', 'genres']]
        results['match_score'] = total_scores[top_25_indices]

        return results

# --- RUNNER ---
app = InteractiveRecommender(movies, indices, tfidf_matrix, lookups)
app.build_user_profile()
recs = app.get_session_recommendations()
print("\n=== TOP 25 PERSONALIZED PICKS ===")
print(recs)

--- STEP 1: TELL ME WHAT YOU LOVE ---
Enter 3 Favorite Movies (exact titles):
Movie 1: Interstellar
Movie 2: The dark knight rises
Movie 3: A beautiful Mind

Enter 2 Favorite Directors:
Director 1: Christopher Nolan
Director 2: David fincher

Enter 2 Favorite Genres:
Genre 1: thriller
Genre 2: comedy

✅ Profile Built based on 1 movies.

--- STEP 2: WHAT ARE YOU WATCHING NOW? ---
Reference Movie (leave blank if none): Happy Death Day
Keywords/Mood (e.g., 'dark space travel'): Dark
   -> Match found with profile! Personalizing...

=== TOP 25 PERSONALIZED PICKS ===
                                     title  vote_average           director  \
46                                   Se7en         8.377       davidfincher
17346                The Dark Knight Rises         7.789   christophernolan
66470                                Tenet         7.176   christophernolan
5258                              Insomnia         6.956   christophernolan
11385                               Zodiac         7.526       davidfincher
12841  The Curious Case of Benjamin Button         7.595       davidfincher
4102                               Memento         8.178   christophernolan
1556                              The Game         7.600       davidfincher
2848                            Fight Club         8.438       davidfincher
1278                                Alien³         6.379       davidfincher
5136                            Panic Room         6.792       davidfincher
14844                            Inception         8.370   christophernolan
15139                   The Social Network         7.371       davidfincher
12165                      The Dark Knight         8.524   christophernolan
47062                              Dunkirk         7.450   christophernolan
17386      The Girl with the Dragon Tattoo         7.400       davidfincher
9960                         Batman Begins         7.700   christophernolan
69176                                 Mank         6.684       davidfincher
2471                             Following         7.100   christophernolan
21636                            Gone Girl         7.890       davidfincher
84910                          Oppenheimer         8.044   christophernolan
11115                         The Prestige         8.205   christophernolan
51565                        The Forlorned         0.000        andrewwiest
47356                 I Am So Proud of You         7.500      donhertzfeldt
39620                             Holidays         4.943  anthonyscottburns

                                     genres  match_score
46               [Crime, Mystery, Thriller]     0.256626
17346      [Action, Crime, Drama, Thriller]     0.247709
66470   [Action, Thriller, Science Fiction]     0.217951
5258               [Thriller, Crime, Drama]     0.212180
11385            [Crime, Mystery, Thriller]     0.207384
12841             [Drama, Fantasy, Romance]     0.206123
4102                    [Mystery, Thriller]     0.204977
1556             [Drama, Thriller, Mystery]     0.202857
2848                      [Drama, Thriller]     0.202690
1278      [Science Fiction, Action, Horror]     0.202212
5136               [Crime, Drama, Thriller]     0.202117
14844  [Action, Science Fiction, Adventure]     0.200000
15139                               [Drama]     0.200000
12165      [Drama, Action, Crime, Thriller]     0.200000
47062                  [War, Action, Drama]     0.200000
17386            [Thriller, Crime, Mystery]     0.200000
9960                 [Drama, Crime, Action]     0.200000
69176                      [Drama, History]     0.200000
2471                      [Drama, Thriller]     0.200000
21636            [Mystery, Thriller, Drama]     0.200000
84910                      [Drama, History]     0.200000
11115     [Drama, Mystery, Science Fiction]     0.200000
51565           [Horror, Mystery, Thriller]     0.182504
47356                    [Animation, Drama]     0.172318
39620    [Comedy, Horror, Fantasy, Mystery]     0.155658